name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: CI on analyseJava project
    runs-on: ubuntu-latest

    steps:
    - name: 1 - Code checkout
      uses: actions/checkout@v4
      
    - name: 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: 3 - Test project Build
      run: mvn -B clean compile --file pom.xml

  test:
    name: CI lancement des Tests Unitaires
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: 1 - Code checkout
        uses: actions/checkout@v3

      - name: 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 3 - Launch Unit Tests
        run: mvn -B test --file pom.xml